'use strict'

/*
  Produce a MagicMirror config.js as a string for a given scenario.
*/

function buildConfig(scenario) {
  const moduleConfig = JSON.stringify(scenario.moduleConfig, null, 2)
  return `// AUTOGENERATED — scenario: ${scenario.name}
module.exports = {
  address: '0.0.0.0',
  port: ${scenario.port ?? 8080},
  ipWhitelist: [],
  language: 'en',
  locale: 'en-US',
  logLevel: ['INFO', 'LOG', 'WARN', 'ERROR'],
  timeFormat: 12,
  units: 'imperial',
  modules: [
    {
      module: 'MMM-MyScoreboard',
      position: 'top_left',
      config: ${moduleConfig},
    },
  ],
}
`
}

module.exports = { buildConfig }
